# Generated by Django 5.2.6 on 2025-09-06 16:37

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.resume_pdf_upload_path),
        ),
    ]
