# Generated by Django 5.2.6 on 2025-09-06 17:13

import django.db.models.deletion
import django.utils.timezone
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_resume', models.FileField(blank=True, null=True, upload_to=jobs.models.application_resume_upload_path)),
                ('cover_letter', models.TextField(blank=True)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled')], default='applied', max_length=32)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.resume')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
