# Generated by Django 5.2.6 on 2025-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="Role or job title (e.g. 'python developer')", max_length=128)),
                ('category', models.CharField(choices=[('pyq', 'Past Year Question (PYQ)'), ('important', 'Important'), ('must', 'Must Do'), ('concept', 'Concept / Explanation')], default='important', max_length=32)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags (e.g. django,rest,algorithms)', max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(blank=True, help_text='Optional: easy/medium/hard', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='interview_i_role_9af953_idx'), models.Index(fields=['category'], name='interview_i_categor_edbdb1_idx')],
            },
        ),
    ]
