# Generated by Django 5.2.6 on 2025-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='interviewquestion',
            name='interview_i_role_9af953_idx',
        ),
        migrations.RemoveIndex(
            model_name='interviewquestion',
            name='interview_i_categor_edbdb1_idx',
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('pyq', 'Python Questions'), ('sys', 'System Design')], db_index=True, default='important', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='role',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='tags',
            field=models.CharField(blank=True, help_text='comma-separated tags', max_length=255),
        ),
    ]
