# Generated by Django 5.2.6 on 2025-09-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_website_user_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
    ]
